name: wedding
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  intro_views_flutter: ^2.8.1
  cupertino_icons: ^0.1.3
  solid_bottom_sheet: ^0.1.9
  video_player: ^0.10.11+2
  chewie: ^0.9.10
  flutter_swiper: ^1.1.6
  font_awesome_flutter: ^8.8.1
  flutter_staggered_grid_view: ^0.3.1
  flutter_countdown_timer: ^1.1.0
  google_maps_flutter: ^0.4.0
  geolocator: ^5.3.2+2
  shared_preferences: ^0.5.8
 

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/images/pic1.jpg
    - assets/images/pic2.jpg
    - assets/images/pic3.jpg
    - assets/images/main_app_bar.png
    - assets/images/nicholas.png
    - assets/images/vanessa.png
    - assets/images/flowers.png
    - assets/images/side_flower1.png
    - assets/images/side_flower2.png
    - assets/videos/wedding_video.m4v
    - assets/images/boy.png
    - assets/images/girl.png
    - assets/images/couple.png
    - assets/images/heart.png
    - assets/images/text.png
    - assets/images/wedding.png
    - assets/images/gallery_top.png
    - assets/images/holiday_tour1.png
    - assets/images/holiday_tour2.png
    - assets/images/holiday_tour3.png
    - assets/images/pre_wedding1.png
    - assets/images/pre_wedding2.png
    - assets/images/pre_wedding3.png
    - assets/images/pre_wedding4.png
    - assets/images/pre_wedding5.png
    - assets/images/event_top.png
    - assets/images/heart_backward.png
    - assets/images/heart_forward.png
    - assets/images/shadow.png
    - assets/images/special_event.png
    - assets/images/wedding_details.png
    - assets/images/map.png
    - assets/images/gmail.png
    - assets/images/insta.png
    - assets/images/whatsapp.png
    - assets/images/robb_stark.png

    



  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Bold.ttf
        - asset: assets/fonts/BebasNeue-Book.ttf
        - asset: assets/fonts/BebasNeue-Light.ttf
        - asset: assets/fonts/BebasNeue-Regular.ttf
        - asset: assets/fonts/BebasNeue-Thin.ttf

    - family: Gilroy
      fonts:
        - asset: assets/fonts/Radomir Tinkov - Gilroy-Black.otf
        - asset: assets/fonts/Radomir Tinkov - Gilroy-Bold.otf
        - asset: assets/fonts/Radomir Tinkov - Gilroy-ExtraBold.otf
        - asset: assets/fonts/Radomir Tinkov - Gilroy-Heavy.otf
        - asset: assets/fonts/Radomir Tinkov - Gilroy-Light.otf
        - asset: assets/fonts/Radomir Tinkov - Gilroy-Medium.otf
        - asset: assets/fonts/Radomir Tinkov - Gilroy-Regular.otf
        - asset: assets/fonts/Radomir Tinkov - Gilroy-Thin.otf
          
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-LightItalic.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf

    - family: Rouge_Script
      fonts:
        - asset: assets/fonts/RougeScript-Regular.ttf

    - family: Constantia-Font
      fonts:
        - asset: assets/fonts/Constantia Font.ttf
        
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
